### ISSUE TITLE
Ability to select background color

### ISSUE THREAD

**Issue by manojsinghnegiwd** [manojsinghnegiwd/quick-cover#4]
Ability to add a background color by either specifying the hex code or picking the color from color picker.

Please use `<ChromePicker />` from https://casesandberg.github.io/react-color/ as color picker.

**Comment by manojsinghnegiwd** [comment]
We also need some text input box where a user can directly input background color rather than picking a color. Please ask for clarification if you have any questions.

**Comment by rocksinghajay** [comment]
We have already this features in the chrome colour picker. Please close this issue asap!

**Comment by manojsinghnegiwd** [comment]
Thanks
