### ISSUE TITLE
Ability to download current canvas

### ISSUE THREAD

**Issue by manojsinghnegiwd** [manojsinghnegiwd/quick-cover#8]
I need a button which says `Download` by clicking on it user can download current SVG canvas from the browser as a PNG.

My best guess to solve this problem will be converting the current SVG canvas to base64 and then download it as a PNG.

**Comment by rocksinghajay** [comment]
Okay, @manojsinghnegiwd today I am working on that issue.

**Comment by manojsinghnegiwd** [comment]
@rocksinghajay Please check this maybe this will help https://stackoverflow.com/questions/28226677/save-inline-svg-as-jpeg-png-svg
