### ISSUE TITLE
Ability to specify SVG canvas width and height

### ISSUE THREAD

**Issue by manojsinghnegiwd** [manojsinghnegiwd/quick-cover#9]
I want to create a new Home Page route where the user can enter `width` and `height` and have a button which says `Create`.

Once clicked on that button redirect page to our editing area and set the SVG canvas `width` and `height` to what user entered.

**Comment by rocksinghajay** [comment]
This issue is fixed and here is the pull request: https://github.com/manojsinghnegiwd/quick-cover/pull/18 @manojsinghnegiwd @puranchand
